# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
 - linux
 - osx

r:
  - 4.0

addons:
       apt:
         update: true
         sources:
           - sourceline: 'ppa:opencpu/imagemagick'
         packages:
           - libmagick++-dev

before_install: R -e 'source("https://install-github.me/r-lib/remotes")'
